# Generated by Django 3.2.3 on 2022-03-17 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlineexamapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('mobile', models.CharField(max_length=100)),
                ('message', models.TextField()),
            ],
        ),
    ]
