# Generated by Django 3.2.3 on 2022-03-18 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlineexamapp', '0003_auto_20220318_1422'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='course',
            field=models.CharField(default='', max_length=100),
        ),
    ]
