# Generated by Django 3.2.3 on 2022-03-22 16:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('onlineexamapp', '0006_coursedetail'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option1', models.CharField(max_length=100)),
                ('option2', models.CharField(max_length=100)),
                ('option3', models.CharField(max_length=100)),
                ('option4', models.CharField(max_length=100)),
                ('answer', models.CharField(max_length=100)),
                ('courseName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='onlineexamapp.coursedetail')),
            ],
        ),
    ]
