# Generated by Django 3.2.3 on 2022-03-26 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onlineexamapp', '0009_rename_coursename_questiondetail_coursedetail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='questiondetail',
            old_name='courseDetail',
            new_name='courseName',
        ),
    ]
