# Generated by Django 3.2.3 on 2022-03-26 17:20

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('onlineexamapp', '0010_rename_coursedetail_questiondetail_coursename'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('testCourse', models.CharField(max_length=100)),
                ('marks', models.PositiveIntegerField()),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='onlineexamapp.coursedetail')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='onlineexamapp.user')),
            ],
        ),
    ]
