# Generated by Django 3.2.3 on 2022-03-29 17:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('onlineexamapp', '0011_testresult'),
    ]

    operations = [
        migrations.CreateModel(
            name='FacultyCourses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facultyCourse', models.CharField(max_length=100)),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='onlineexamapp.user')),
            ],
        ),
    ]
